version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod

linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - goconst
  settings:
    govet:
      enable:
        - shadow
    revive:
      severity: warning

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - avito-assignment-2025-autumn


issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
