// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/derletzte256/avito-assignment-2025-autumn/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPullRequestRepository creates a new instance of MockPullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type MockPullRequestRepository struct {
	mock.Mock
}

type MockPullRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestRepository) EXPECT() *MockPullRequestRepository_Expecter {
	return &MockPullRequestRepository_Expecter{mock: &_m.Mock}
}

// AddNewReviewer provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) AddNewReviewer(ctx context.Context, prID string, userID string) error {
	ret := _mock.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddNewReviewer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_AddNewReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewReviewer'
type MockPullRequestRepository_AddNewReviewer_Call struct {
	*mock.Call
}

// AddNewReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - userID string
func (_e *MockPullRequestRepository_Expecter) AddNewReviewer(ctx interface{}, prID interface{}, userID interface{}) *MockPullRequestRepository_AddNewReviewer_Call {
	return &MockPullRequestRepository_AddNewReviewer_Call{Call: _e.mock.On("AddNewReviewer", ctx, prID, userID)}
}

func (_c *MockPullRequestRepository_AddNewReviewer_Call) Run(run func(ctx context.Context, prID string, userID string)) *MockPullRequestRepository_AddNewReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_AddNewReviewer_Call) Return(err error) *MockPullRequestRepository_AddNewReviewer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_AddNewReviewer_Call) RunAndReturn(run func(ctx context.Context, prID string, userID string) error) *MockPullRequestRepository_AddNewReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// AddReviewersBatch provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) AddReviewersBatch(ctx context.Context, records []*entity.ReviewRecord) error {
	ret := _mock.Called(ctx, records)

	if len(ret) == 0 {
		panic("no return value specified for AddReviewersBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entity.ReviewRecord) error); ok {
		r0 = returnFunc(ctx, records)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_AddReviewersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReviewersBatch'
type MockPullRequestRepository_AddReviewersBatch_Call struct {
	*mock.Call
}

// AddReviewersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - records []*entity.ReviewRecord
func (_e *MockPullRequestRepository_Expecter) AddReviewersBatch(ctx interface{}, records interface{}) *MockPullRequestRepository_AddReviewersBatch_Call {
	return &MockPullRequestRepository_AddReviewersBatch_Call{Call: _e.mock.On("AddReviewersBatch", ctx, records)}
}

func (_c *MockPullRequestRepository_AddReviewersBatch_Call) Run(run func(ctx context.Context, records []*entity.ReviewRecord)) *MockPullRequestRepository_AddReviewersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entity.ReviewRecord
		if args[1] != nil {
			arg1 = args[1].([]*entity.ReviewRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_AddReviewersBatch_Call) Return(err error) *MockPullRequestRepository_AddReviewersBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_AddReviewersBatch_Call) RunAndReturn(run func(ctx context.Context, records []*entity.ReviewRecord) error) *MockPullRequestRepository_AddReviewersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// AssignReviewers provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) AssignReviewers(ctx context.Context, prID string, reviewerIDs []string) error {
	ret := _mock.Called(ctx, prID, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignReviewers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, prID, reviewerIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_AssignReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignReviewers'
type MockPullRequestRepository_AssignReviewers_Call struct {
	*mock.Call
}

// AssignReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - reviewerIDs []string
func (_e *MockPullRequestRepository_Expecter) AssignReviewers(ctx interface{}, prID interface{}, reviewerIDs interface{}) *MockPullRequestRepository_AssignReviewers_Call {
	return &MockPullRequestRepository_AssignReviewers_Call{Call: _e.mock.On("AssignReviewers", ctx, prID, reviewerIDs)}
}

func (_c *MockPullRequestRepository_AssignReviewers_Call) Run(run func(ctx context.Context, prID string, reviewerIDs []string)) *MockPullRequestRepository_AssignReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_AssignReviewers_Call) Return(err error) *MockPullRequestRepository_AssignReviewers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_AssignReviewers_Call) RunAndReturn(run func(ctx context.Context, prID string, reviewerIDs []string) error) *MockPullRequestRepository_AssignReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPullRequestIDExists provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) CheckPullRequestIDExists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckPullRequestIDExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_CheckPullRequestIDExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPullRequestIDExists'
type MockPullRequestRepository_CheckPullRequestIDExists_Call struct {
	*mock.Call
}

// CheckPullRequestIDExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPullRequestRepository_Expecter) CheckPullRequestIDExists(ctx interface{}, id interface{}) *MockPullRequestRepository_CheckPullRequestIDExists_Call {
	return &MockPullRequestRepository_CheckPullRequestIDExists_Call{Call: _e.mock.On("CheckPullRequestIDExists", ctx, id)}
}

func (_c *MockPullRequestRepository_CheckPullRequestIDExists_Call) Run(run func(ctx context.Context, id string)) *MockPullRequestRepository_CheckPullRequestIDExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_CheckPullRequestIDExists_Call) Return(b bool, err error) *MockPullRequestRepository_CheckPullRequestIDExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPullRequestRepository_CheckPullRequestIDExists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *MockPullRequestRepository_CheckPullRequestIDExists_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) Create(ctx context.Context, pr *entity.PullRequest) error {
	ret := _mock.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.PullRequest) error); ok {
		r0 = returnFunc(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPullRequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *entity.PullRequest
func (_e *MockPullRequestRepository_Expecter) Create(ctx interface{}, pr interface{}) *MockPullRequestRepository_Create_Call {
	return &MockPullRequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, pr)}
}

func (_c *MockPullRequestRepository_Create_Call) Run(run func(ctx context.Context, pr *entity.PullRequest)) *MockPullRequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.PullRequest
		if args[1] != nil {
			arg1 = args[1].(*entity.PullRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_Create_Call) Return(err error) *MockPullRequestRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_Create_Call) RunAndReturn(run func(ctx context.Context, pr *entity.PullRequest) error) *MockPullRequestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorStatisticsForUsers provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetAuthorStatisticsForUsers(ctx context.Context) (map[string]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorStatisticsForUsers")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetAuthorStatisticsForUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorStatisticsForUsers'
type MockPullRequestRepository_GetAuthorStatisticsForUsers_Call struct {
	*mock.Call
}

// GetAuthorStatisticsForUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPullRequestRepository_Expecter) GetAuthorStatisticsForUsers(ctx interface{}) *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call {
	return &MockPullRequestRepository_GetAuthorStatisticsForUsers_Call{Call: _e.mock.On("GetAuthorStatisticsForUsers", ctx)}
}

func (_c *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call) Run(run func(ctx context.Context)) *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call) Return(stringToInt map[string]int, err error) *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call) RunAndReturn(run func(ctx context.Context) (map[string]int, error)) *MockPullRequestRepository_GetAuthorStatisticsForUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenAndMergedReviewStatisticsForUsers provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetOpenAndMergedReviewStatisticsForUsers(ctx context.Context) (map[string]int, map[string]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenAndMergedReviewStatisticsForUsers")
	}

	var r0 map[string]int
	var r1 map[string]int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]int, map[string]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) map[string]int); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenAndMergedReviewStatisticsForUsers'
type MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call struct {
	*mock.Call
}

// GetOpenAndMergedReviewStatisticsForUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPullRequestRepository_Expecter) GetOpenAndMergedReviewStatisticsForUsers(ctx interface{}) *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call {
	return &MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call{Call: _e.mock.On("GetOpenAndMergedReviewStatisticsForUsers", ctx)}
}

func (_c *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call) Run(run func(ctx context.Context)) *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call) Return(stringToInt map[string]int, stringToInt1 map[string]int, err error) *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call {
	_c.Call.Return(stringToInt, stringToInt1, err)
	return _c
}

func (_c *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call) RunAndReturn(run func(ctx context.Context) (map[string]int, map[string]int, error)) *MockPullRequestRepository_GetOpenAndMergedReviewStatisticsForUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullRequestByID provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetPullRequestByID(ctx context.Context, id string) (*entity.PullRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByID")
	}

	var r0 *entity.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.PullRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.PullRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetPullRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestByID'
type MockPullRequestRepository_GetPullRequestByID_Call struct {
	*mock.Call
}

// GetPullRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPullRequestRepository_Expecter) GetPullRequestByID(ctx interface{}, id interface{}) *MockPullRequestRepository_GetPullRequestByID_Call {
	return &MockPullRequestRepository_GetPullRequestByID_Call{Call: _e.mock.On("GetPullRequestByID", ctx, id)}
}

func (_c *MockPullRequestRepository_GetPullRequestByID_Call) Run(run func(ctx context.Context, id string)) *MockPullRequestRepository_GetPullRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetPullRequestByID_Call) Return(pullRequest *entity.PullRequest, err error) *MockPullRequestRepository_GetPullRequestByID_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockPullRequestRepository_GetPullRequestByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.PullRequest, error)) *MockPullRequestRepository_GetPullRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullRequestsByReviewerID provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetPullRequestsByReviewerID(ctx context.Context, userID string) ([]*entity.PullRequest, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestsByReviewerID")
	}

	var r0 []*entity.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.PullRequest, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.PullRequest); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetPullRequestsByReviewerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestsByReviewerID'
type MockPullRequestRepository_GetPullRequestsByReviewerID_Call struct {
	*mock.Call
}

// GetPullRequestsByReviewerID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPullRequestRepository_Expecter) GetPullRequestsByReviewerID(ctx interface{}, userID interface{}) *MockPullRequestRepository_GetPullRequestsByReviewerID_Call {
	return &MockPullRequestRepository_GetPullRequestsByReviewerID_Call{Call: _e.mock.On("GetPullRequestsByReviewerID", ctx, userID)}
}

func (_c *MockPullRequestRepository_GetPullRequestsByReviewerID_Call) Run(run func(ctx context.Context, userID string)) *MockPullRequestRepository_GetPullRequestsByReviewerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetPullRequestsByReviewerID_Call) Return(pullRequests []*entity.PullRequest, err error) *MockPullRequestRepository_GetPullRequestsByReviewerID_Call {
	_c.Call.Return(pullRequests, err)
	return _c
}

func (_c *MockPullRequestRepository_GetPullRequestsByReviewerID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.PullRequest, error)) *MockPullRequestRepository_GetPullRequestsByReviewerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewersByPullRequestID provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetReviewersByPullRequestID(ctx context.Context, id string) ([]string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewersByPullRequestID")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetReviewersByPullRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewersByPullRequestID'
type MockPullRequestRepository_GetReviewersByPullRequestID_Call struct {
	*mock.Call
}

// GetReviewersByPullRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPullRequestRepository_Expecter) GetReviewersByPullRequestID(ctx interface{}, id interface{}) *MockPullRequestRepository_GetReviewersByPullRequestID_Call {
	return &MockPullRequestRepository_GetReviewersByPullRequestID_Call{Call: _e.mock.On("GetReviewersByPullRequestID", ctx, id)}
}

func (_c *MockPullRequestRepository_GetReviewersByPullRequestID_Call) Run(run func(ctx context.Context, id string)) *MockPullRequestRepository_GetReviewersByPullRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetReviewersByPullRequestID_Call) Return(strings []string, err error) *MockPullRequestRepository_GetReviewersByPullRequestID_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPullRequestRepository_GetReviewersByPullRequestID_Call) RunAndReturn(run func(ctx context.Context, id string) ([]string, error)) *MockPullRequestRepository_GetReviewersByPullRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewersByPullRequestIDs provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetReviewersByPullRequestIDs(ctx context.Context, prIDs []string) (map[string][]string, error) {
	ret := _mock.Called(ctx, prIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewersByPullRequestIDs")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string][]string, error)); ok {
		return returnFunc(ctx, prIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string][]string); ok {
		r0 = returnFunc(ctx, prIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, prIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetReviewersByPullRequestIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewersByPullRequestIDs'
type MockPullRequestRepository_GetReviewersByPullRequestIDs_Call struct {
	*mock.Call
}

// GetReviewersByPullRequestIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - prIDs []string
func (_e *MockPullRequestRepository_Expecter) GetReviewersByPullRequestIDs(ctx interface{}, prIDs interface{}) *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call {
	return &MockPullRequestRepository_GetReviewersByPullRequestIDs_Call{Call: _e.mock.On("GetReviewersByPullRequestIDs", ctx, prIDs)}
}

func (_c *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call) Run(run func(ctx context.Context, prIDs []string)) *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call) Return(stringToStrings map[string][]string, err error) *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call) RunAndReturn(run func(ctx context.Context, prIDs []string) (map[string][]string, error)) *MockPullRequestRepository_GetReviewersByPullRequestIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewsByReviewerIDs provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) GetReviewsByReviewerIDs(ctx context.Context, reviewerIDs []string) ([]*entity.ReviewRecord, error) {
	ret := _mock.Called(ctx, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsByReviewerIDs")
	}

	var r0 []*entity.ReviewRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*entity.ReviewRecord, error)); ok {
		return returnFunc(ctx, reviewerIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*entity.ReviewRecord); ok {
		r0 = returnFunc(ctx, reviewerIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ReviewRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, reviewerIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullRequestRepository_GetReviewsByReviewerIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsByReviewerIDs'
type MockPullRequestRepository_GetReviewsByReviewerIDs_Call struct {
	*mock.Call
}

// GetReviewsByReviewerIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerIDs []string
func (_e *MockPullRequestRepository_Expecter) GetReviewsByReviewerIDs(ctx interface{}, reviewerIDs interface{}) *MockPullRequestRepository_GetReviewsByReviewerIDs_Call {
	return &MockPullRequestRepository_GetReviewsByReviewerIDs_Call{Call: _e.mock.On("GetReviewsByReviewerIDs", ctx, reviewerIDs)}
}

func (_c *MockPullRequestRepository_GetReviewsByReviewerIDs_Call) Run(run func(ctx context.Context, reviewerIDs []string)) *MockPullRequestRepository_GetReviewsByReviewerIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_GetReviewsByReviewerIDs_Call) Return(reviewRecords []*entity.ReviewRecord, err error) *MockPullRequestRepository_GetReviewsByReviewerIDs_Call {
	_c.Call.Return(reviewRecords, err)
	return _c
}

func (_c *MockPullRequestRepository_GetReviewsByReviewerIDs_Call) RunAndReturn(run func(ctx context.Context, reviewerIDs []string) ([]*entity.ReviewRecord, error)) *MockPullRequestRepository_GetReviewsByReviewerIDs_Call {
	_c.Call.Return(run)
	return _c
}

// MergePullRequestByID provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) MergePullRequestByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequestByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_MergePullRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePullRequestByID'
type MockPullRequestRepository_MergePullRequestByID_Call struct {
	*mock.Call
}

// MergePullRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPullRequestRepository_Expecter) MergePullRequestByID(ctx interface{}, id interface{}) *MockPullRequestRepository_MergePullRequestByID_Call {
	return &MockPullRequestRepository_MergePullRequestByID_Call{Call: _e.mock.On("MergePullRequestByID", ctx, id)}
}

func (_c *MockPullRequestRepository_MergePullRequestByID_Call) Run(run func(ctx context.Context, id string)) *MockPullRequestRepository_MergePullRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_MergePullRequestByID_Call) Return(err error) *MockPullRequestRepository_MergePullRequestByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_MergePullRequestByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockPullRequestRepository_MergePullRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReviewer provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) RemoveReviewer(ctx context.Context, prID string, userID string) error {
	ret := _mock.Called(ctx, prID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, prID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_RemoveReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReviewer'
type MockPullRequestRepository_RemoveReviewer_Call struct {
	*mock.Call
}

// RemoveReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - userID string
func (_e *MockPullRequestRepository_Expecter) RemoveReviewer(ctx interface{}, prID interface{}, userID interface{}) *MockPullRequestRepository_RemoveReviewer_Call {
	return &MockPullRequestRepository_RemoveReviewer_Call{Call: _e.mock.On("RemoveReviewer", ctx, prID, userID)}
}

func (_c *MockPullRequestRepository_RemoveReviewer_Call) Run(run func(ctx context.Context, prID string, userID string)) *MockPullRequestRepository_RemoveReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_RemoveReviewer_Call) Return(err error) *MockPullRequestRepository_RemoveReviewer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_RemoveReviewer_Call) RunAndReturn(run func(ctx context.Context, prID string, userID string) error) *MockPullRequestRepository_RemoveReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReviewersBatch provides a mock function for the type MockPullRequestRepository
func (_mock *MockPullRequestRepository) RemoveReviewersBatch(ctx context.Context, records []*entity.ReviewRecord) error {
	ret := _mock.Called(ctx, records)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReviewersBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entity.ReviewRecord) error); ok {
		r0 = returnFunc(ctx, records)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullRequestRepository_RemoveReviewersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReviewersBatch'
type MockPullRequestRepository_RemoveReviewersBatch_Call struct {
	*mock.Call
}

// RemoveReviewersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - records []*entity.ReviewRecord
func (_e *MockPullRequestRepository_Expecter) RemoveReviewersBatch(ctx interface{}, records interface{}) *MockPullRequestRepository_RemoveReviewersBatch_Call {
	return &MockPullRequestRepository_RemoveReviewersBatch_Call{Call: _e.mock.On("RemoveReviewersBatch", ctx, records)}
}

func (_c *MockPullRequestRepository_RemoveReviewersBatch_Call) Run(run func(ctx context.Context, records []*entity.ReviewRecord)) *MockPullRequestRepository_RemoveReviewersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entity.ReviewRecord
		if args[1] != nil {
			arg1 = args[1].([]*entity.ReviewRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullRequestRepository_RemoveReviewersBatch_Call) Return(err error) *MockPullRequestRepository_RemoveReviewersBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullRequestRepository_RemoveReviewersBatch_Call) RunAndReturn(run func(ctx context.Context, records []*entity.ReviewRecord) error) *MockPullRequestRepository_RemoveReviewersBatch_Call {
	_c.Call.Return(run)
	return _c
}
