// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/derletzte256/avito-assignment-2025-autumn/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// CheckTeamNameExists provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) CheckTeamNameExists(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CheckTeamNameExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_CheckTeamNameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckTeamNameExists'
type MockTeamRepository_CheckTeamNameExists_Call struct {
	*mock.Call
}

// CheckTeamNameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) CheckTeamNameExists(ctx interface{}, name interface{}) *MockTeamRepository_CheckTeamNameExists_Call {
	return &MockTeamRepository_CheckTeamNameExists_Call{Call: _e.mock.On("CheckTeamNameExists", ctx, name)}
}

func (_c *MockTeamRepository_CheckTeamNameExists_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_CheckTeamNameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_CheckTeamNameExists_Call) Return(b bool, err error) *MockTeamRepository_CheckTeamNameExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTeamRepository_CheckTeamNameExists_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *MockTeamRepository_CheckTeamNameExists_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Create(ctx context.Context, team *entity.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - team *entity.Team
func (_e *MockTeamRepository_Expecter) Create(ctx interface{}, team interface{}) *MockTeamRepository_Create_Call {
	return &MockTeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, team)}
}

func (_c *MockTeamRepository_Create_Call) Run(run func(ctx context.Context, team *entity.Team)) *MockTeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Team
		if args[1] != nil {
			arg1 = args[1].(*entity.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Create_Call) Return(err error) *MockTeamRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Create_Call) RunAndReturn(run func(ctx context.Context, team *entity.Team) error) *MockTeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByName(ctx context.Context, name string) (*entity.Team, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Team, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Team); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTeamRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockTeamRepository_GetByName_Call {
	return &MockTeamRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTeamRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByName_Call) Return(team *entity.Team, err error) *MockTeamRepository_GetByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entity.Team, error)) *MockTeamRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}
