// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/derletzte256/avito-assignment-2025-autumn/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CheckUserExists provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CheckUserExists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_CheckUserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserExists'
type MockUserRepository_CheckUserExists_Call struct {
	*mock.Call
}

// CheckUserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) CheckUserExists(ctx interface{}, id interface{}) *MockUserRepository_CheckUserExists_Call {
	return &MockUserRepository_CheckUserExists_Call{Call: _e.mock.On("CheckUserExists", ctx, id)}
}

func (_c *MockUserRepository_CheckUserExists_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_CheckUserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_CheckUserExists_Call) Return(b bool, err error) *MockUserRepository_CheckUserExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_CheckUserExists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *MockUserRepository_CheckUserExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateBatch(ctx context.Context, members []*entity.Member, teamName string) error {
	ret := _mock.Called(ctx, members, teamName)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entity.Member, string) error); ok {
		r0 = returnFunc(ctx, members, teamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockUserRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - members []*entity.Member
//   - teamName string
func (_e *MockUserRepository_Expecter) CreateBatch(ctx interface{}, members interface{}, teamName interface{}) *MockUserRepository_CreateBatch_Call {
	return &MockUserRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, members, teamName)}
}

func (_c *MockUserRepository_CreateBatch_Call) Run(run func(ctx context.Context, members []*entity.Member, teamName string)) *MockUserRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entity.Member
		if args[1] != nil {
			arg1 = args[1].([]*entity.Member)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateBatch_Call) Return(err error) *MockUserRepository_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, members []*entity.Member, teamName string) error) *MockUserRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateUsers provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeactivateUsers(ctx context.Context, ids []string) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeactivateUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateUsers'
type MockUserRepository_DeactivateUsers_Call struct {
	*mock.Call
}

// DeactivateUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockUserRepository_Expecter) DeactivateUsers(ctx interface{}, ids interface{}) *MockUserRepository_DeactivateUsers_Call {
	return &MockUserRepository_DeactivateUsers_Call{Call: _e.mock.On("DeactivateUsers", ctx, ids)}
}

func (_c *MockUserRepository_DeactivateUsers_Call) Run(run func(ctx context.Context, ids []string)) *MockUserRepository_DeactivateUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeactivateUsers_Call) Return(err error) *MockUserRepository_DeactivateUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeactivateUsers_Call) RunAndReturn(run func(ctx context.Context, ids []string) error) *MockUserRepository_DeactivateUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FindExistingByIDs provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindExistingByIDs(ctx context.Context, ids []string) (map[string]struct{}, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindExistingByIDs")
	}

	var r0 map[string]struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]struct{}, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]struct{}); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindExistingByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExistingByIDs'
type MockUserRepository_FindExistingByIDs_Call struct {
	*mock.Call
}

// FindExistingByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockUserRepository_Expecter) FindExistingByIDs(ctx interface{}, ids interface{}) *MockUserRepository_FindExistingByIDs_Call {
	return &MockUserRepository_FindExistingByIDs_Call{Call: _e.mock.On("FindExistingByIDs", ctx, ids)}
}

func (_c *MockUserRepository_FindExistingByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockUserRepository_FindExistingByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindExistingByIDs_Call) Return(stringToVal map[string]struct{}, err error) *MockUserRepository_FindExistingByIDs_Call {
	_c.Call.Return(stringToVal, err)
	return _c
}

func (_c *MockUserRepository_FindExistingByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) (map[string]struct{}, error)) *MockUserRepository_FindExistingByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveUsersIDsByTeamName provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetActiveUsersIDsByTeamName(ctx context.Context, teamName string, excludeIDs []string) ([]string, error) {
	ret := _mock.Called(ctx, teamName, excludeIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveUsersIDsByTeamName")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, error)); ok {
		return returnFunc(ctx, teamName, excludeIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, teamName, excludeIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, teamName, excludeIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetActiveUsersIDsByTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveUsersIDsByTeamName'
type MockUserRepository_GetActiveUsersIDsByTeamName_Call struct {
	*mock.Call
}

// GetActiveUsersIDsByTeamName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - excludeIDs []string
func (_e *MockUserRepository_Expecter) GetActiveUsersIDsByTeamName(ctx interface{}, teamName interface{}, excludeIDs interface{}) *MockUserRepository_GetActiveUsersIDsByTeamName_Call {
	return &MockUserRepository_GetActiveUsersIDsByTeamName_Call{Call: _e.mock.On("GetActiveUsersIDsByTeamName", ctx, teamName, excludeIDs)}
}

func (_c *MockUserRepository_GetActiveUsersIDsByTeamName_Call) Run(run func(ctx context.Context, teamName string, excludeIDs []string)) *MockUserRepository_GetActiveUsersIDsByTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetActiveUsersIDsByTeamName_Call) Return(strings []string, err error) *MockUserRepository_GetActiveUsersIDsByTeamName_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUserRepository_GetActiveUsersIDsByTeamName_Call) RunAndReturn(run func(ctx context.Context, teamName string, excludeIDs []string) ([]string, error)) *MockUserRepository_GetActiveUsersIDsByTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsersIDs provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetAllUsersIDs(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetAllUsersIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsersIDs'
type MockUserRepository_GetAllUsersIDs_Call struct {
	*mock.Call
}

// GetAllUsersIDs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) GetAllUsersIDs(ctx interface{}) *MockUserRepository_GetAllUsersIDs_Call {
	return &MockUserRepository_GetAllUsersIDs_Call{Call: _e.mock.On("GetAllUsersIDs", ctx)}
}

func (_c *MockUserRepository_GetAllUsersIDs_Call) Run(run func(ctx context.Context)) *MockUserRepository_GetAllUsersIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetAllUsersIDs_Call) Return(strings []string, err error) *MockUserRepository_GetAllUsersIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUserRepository_GetAllUsersIDs_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockUserRepository_GetAllUsersIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeamName provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByTeamName(ctx context.Context, teamName string) ([]*entity.Member, error) {
	ret := _mock.Called(ctx, teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamName")
	}

	var r0 []*entity.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Member, error)); ok {
		return returnFunc(ctx, teamName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Member); ok {
		r0 = returnFunc(ctx, teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, teamName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByTeamName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeamName'
type MockUserRepository_GetByTeamName_Call struct {
	*mock.Call
}

// GetByTeamName is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
func (_e *MockUserRepository_Expecter) GetByTeamName(ctx interface{}, teamName interface{}) *MockUserRepository_GetByTeamName_Call {
	return &MockUserRepository_GetByTeamName_Call{Call: _e.mock.On("GetByTeamName", ctx, teamName)}
}

func (_c *MockUserRepository_GetByTeamName_Call) Run(run func(ctx context.Context, teamName string)) *MockUserRepository_GetByTeamName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByTeamName_Call) Return(members []*entity.Member, err error) *MockUserRepository_GetByTeamName_Call {
	_c.Call.Return(members, err)
	return _c
}

func (_c *MockUserRepository_GetByTeamName_Call) RunAndReturn(run func(ctx context.Context, teamName string) ([]*entity.Member, error)) *MockUserRepository_GetByTeamName_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplacementReviewerForPullRequest provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetReplacementReviewerForPullRequest(ctx context.Context, teamName string, excludeUserIDs []string) (*entity.User, error) {
	ret := _mock.Called(ctx, teamName, excludeUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetReplacementReviewerForPullRequest")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (*entity.User, error)); ok {
		return returnFunc(ctx, teamName, excludeUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) *entity.User); ok {
		r0 = returnFunc(ctx, teamName, excludeUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, teamName, excludeUserIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetReplacementReviewerForPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplacementReviewerForPullRequest'
type MockUserRepository_GetReplacementReviewerForPullRequest_Call struct {
	*mock.Call
}

// GetReplacementReviewerForPullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - excludeUserIDs []string
func (_e *MockUserRepository_Expecter) GetReplacementReviewerForPullRequest(ctx interface{}, teamName interface{}, excludeUserIDs interface{}) *MockUserRepository_GetReplacementReviewerForPullRequest_Call {
	return &MockUserRepository_GetReplacementReviewerForPullRequest_Call{Call: _e.mock.On("GetReplacementReviewerForPullRequest", ctx, teamName, excludeUserIDs)}
}

func (_c *MockUserRepository_GetReplacementReviewerForPullRequest_Call) Run(run func(ctx context.Context, teamName string, excludeUserIDs []string)) *MockUserRepository_GetReplacementReviewerForPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetReplacementReviewerForPullRequest_Call) Return(user *entity.User, err error) *MockUserRepository_GetReplacementReviewerForPullRequest_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetReplacementReviewerForPullRequest_Call) RunAndReturn(run func(ctx context.Context, teamName string, excludeUserIDs []string) (*entity.User, error)) *MockUserRepository_GetReplacementReviewerForPullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewersForPullRequest provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetReviewersForPullRequest(ctx context.Context, teamName string, excludeUserID string) ([]*entity.User, error) {
	ret := _mock.Called(ctx, teamName, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewersForPullRequest")
	}

	var r0 []*entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*entity.User, error)); ok {
		return returnFunc(ctx, teamName, excludeUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*entity.User); ok {
		r0 = returnFunc(ctx, teamName, excludeUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, teamName, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetReviewersForPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewersForPullRequest'
type MockUserRepository_GetReviewersForPullRequest_Call struct {
	*mock.Call
}

// GetReviewersForPullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - teamName string
//   - excludeUserID string
func (_e *MockUserRepository_Expecter) GetReviewersForPullRequest(ctx interface{}, teamName interface{}, excludeUserID interface{}) *MockUserRepository_GetReviewersForPullRequest_Call {
	return &MockUserRepository_GetReviewersForPullRequest_Call{Call: _e.mock.On("GetReviewersForPullRequest", ctx, teamName, excludeUserID)}
}

func (_c *MockUserRepository_GetReviewersForPullRequest_Call) Run(run func(ctx context.Context, teamName string, excludeUserID string)) *MockUserRepository_GetReviewersForPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetReviewersForPullRequest_Call) Return(users []*entity.User, err error) *MockUserRepository_GetReviewersForPullRequest_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetReviewersForPullRequest_Call) RunAndReturn(run func(ctx context.Context, teamName string, excludeUserID string) ([]*entity.User, error)) *MockUserRepository_GetReviewersForPullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByID(ctx context.Context, id string) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(user *entity.User, err error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByIDs provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUsersByIDs(ctx context.Context, ids []string) ([]*entity.User, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIDs")
	}

	var r0 []*entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*entity.User, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*entity.User); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUsersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByIDs'
type MockUserRepository_GetUsersByIDs_Call struct {
	*mock.Call
}

// GetUsersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockUserRepository_Expecter) GetUsersByIDs(ctx interface{}, ids interface{}) *MockUserRepository_GetUsersByIDs_Call {
	return &MockUserRepository_GetUsersByIDs_Call{Call: _e.mock.On("GetUsersByIDs", ctx, ids)}
}

func (_c *MockUserRepository_GetUsersByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockUserRepository_GetUsersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUsersByIDs_Call) Return(users []*entity.User, err error) *MockUserRepository_GetUsersByIDs_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetUsersByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]*entity.User, error)) *MockUserRepository_GetUsersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SetIsActive provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetIsActive(ctx context.Context, id string, isActive bool) error {
	ret := _mock.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetIsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIsActive'
type MockUserRepository_SetIsActive_Call struct {
	*mock.Call
}

// SetIsActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isActive bool
func (_e *MockUserRepository_Expecter) SetIsActive(ctx interface{}, id interface{}, isActive interface{}) *MockUserRepository_SetIsActive_Call {
	return &MockUserRepository_SetIsActive_Call{Call: _e.mock.On("SetIsActive", ctx, id, isActive)}
}

func (_c *MockUserRepository_SetIsActive_Call) Run(run func(ctx context.Context, id string, isActive bool)) *MockUserRepository_SetIsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_SetIsActive_Call) Return(err error) *MockUserRepository_SetIsActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetIsActive_Call) RunAndReturn(run func(ctx context.Context, id string, isActive bool) error) *MockUserRepository_SetIsActive_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMembers provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateMembers(ctx context.Context, members []*entity.Member, teamName string) error {
	ret := _mock.Called(ctx, members, teamName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMembers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entity.Member, string) error); ok {
		r0 = returnFunc(ctx, members, teamName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMembers'
type MockUserRepository_UpdateMembers_Call struct {
	*mock.Call
}

// UpdateMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - members []*entity.Member
//   - teamName string
func (_e *MockUserRepository_Expecter) UpdateMembers(ctx interface{}, members interface{}, teamName interface{}) *MockUserRepository_UpdateMembers_Call {
	return &MockUserRepository_UpdateMembers_Call{Call: _e.mock.On("UpdateMembers", ctx, members, teamName)}
}

func (_c *MockUserRepository_UpdateMembers_Call) Run(run func(ctx context.Context, members []*entity.Member, teamName string)) *MockUserRepository_UpdateMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entity.Member
		if args[1] != nil {
			arg1 = args[1].([]*entity.Member)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateMembers_Call) Return(err error) *MockUserRepository_UpdateMembers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateMembers_Call) RunAndReturn(run func(ctx context.Context, members []*entity.Member, teamName string) error) *MockUserRepository_UpdateMembers_Call {
	_c.Call.Return(run)
	return _c
}
